"""
Safe messages (250) — contains scam-like keywords, legitimate transactions, edge cases.
This file is imported by hard_test_500.py.
"""

safe_messages = []

# ── CAT 1: Legitimate bank notifications (25) ──
safe_messages += [("Bank (Legit)", "Safe", m) for m in [
    "HBL: Rs. 5,000 debit from your account at Imtiaz Store on 28-Aug-2026. Balance: Rs. 45,000.",
    "Meezan Bank: Your monthly statement is ready. Download from Meezan mobile app.",
    "UBL: Your salary of Rs. 85,000 has been credited on 01-Sep-2026.",
    "Allied Bank: ATM withdrawal of Rs. 10,000 at Clifton Branch. Balance: Rs. 32,500.",
    "MCB: Your cheque #445521 of Rs. 25,000 has been cleared successfully.",
    "Bank Alfalah: Your credit card bill of Rs. 15,000 is due on 15-Sep-2026.",
    "Faysal Bank: Fixed deposit of Rs. 500,000 matured. Visit branch for renewal.",
    "Standard Chartered: Your account statement for August 2026 is available online.",
    "Askari Bank: Your debit card has been dispatched. Collect from nearest branch.",
    "HBL: Rs. 2,500 received from Muhammad Ali via HBL mobile transfer.",
    "Meezan: Zakat deduction of Rs. 2,500 applied on 1-Ramadan-2026 as per SBP rules.",
    "UBL: Your car loan EMI of Rs. 35,000 deducted on 05-Sep-2026. Next due: 05-Oct.",
    "بینک الفلاح: آپ کے اکاؤنٹ سے Rs. 15,000 کی منتقلی کامیابی سے مکمل ہو گئی ہے۔",
    "Bank Habib: Your foreign remittance of $500 from UAE credited. Rate: 278.50.",
    "Sindh Bank: Your Kissan card has been activated. Visit branch for PIN.",
    "MCB: Annual report 2025-26 available at mcb.com.pk/investors",
    "Allied Bank: Branch timing update — Clifton branch now opens at 9 AM.",
    "HBL mobile: App update available. Version 4.2.1 with new security features.",
    "Faysal Bank: Your account maintenance fee of Rs. 250 deducted for Q3-2026.",
    "UBL: Your term deposit profit of Rs. 12,500 credited. Tax deducted: Rs. 1,875.",
    "Standard Chartered: Quarterly newsletter — Sep 2026 edition now available.",
    "Askari Bank: Your home insurance premium of Rs. 8,000 auto-deducted.",
    "Meezan Islamic: Your Mudarabah profit for August: Rs. 3,200.",
    "Bank Alfalah: Credit card reward points balance: 15,000 points.",
    "HBL: Naya Pakistan certificate purchased Rs. 100,000. Maturity: 3 years.",
]]

# ── CAT 2: Real delivery/e-commerce (25) ──
safe_messages += [("Delivery (Legit)", "Safe", m) for m in [
    "TCS: Your parcel #8834521 is out for delivery. Track at tcs.com.pk",
    "Daraz: Order #7734521 delivered successfully. Rate your experience.",
    "Leopards: Shipment #LP9923847 picked up from Lahore. ETA: 2 days.",
    "Your Foodpanda order from KFC is on the way. ETA: 25 minutes.",
    "Careem: Your ride to DHA Phase 5 is confirmed. Driver: Ahmed, Corolla AXG-1234.",
    "InDrive: Ride accepted. Fare Rs. 450. Driver arriving in 5 minutes.",
    "Swiggy: Your order from Pizza Hut has been prepared. Rider assigned.",
    "Daraz: Your return for order #5566778 has been picked up. Refund in 3-5 days.",
    "PostEx: COD payment of Rs. 3,500 collected from customer. Transfer in 24 hours.",
    "Your Trax shipment #TX998877 has arrived at Karachi hub.",
    "MnP Courier: Document parcel delivered to receiver at 2:30 PM today.",
    "Daraz Flash Sale: Up to 70% off on electronics. Shop now at daraz.pk",
    "Foodpanda: Your order has been delivered. Enjoy your meal!",
    "Careem Food: Order from Al-Baik delivered. Total: Rs. 1,250.",
    "Swiggy: Your subscription renewal of Rs. 299 has been processed.",
    "TCS: Rate card updated. New rates effective 01-Oct-2026.",
    "Daraz Wallet: Rs. 500 refund credited to your wallet.",
    "Yayvo: Order #4455667 shipped. Tracking: YV-2026-88990011.",
    "PostEx: Your shipment has been collected from seller. In transit.",
    "Telemart: Your order #889900 confirmed. Delivery in 3-5 business days.",
    "Shophive: Product dispatched. Invoice emailed to your registered address.",
    "Daraz Mall: Authentic product guaranteed. 14-day return policy.",
    "TCS: Aap ka parcel deliver ho gaya hai. Receiver: Ahmad.",
    "Leopards: Your document delivery to Islamabad completed successfully.",
    "Post office: Registered letter from HBL delivered to your address today.",
]]

# ── CAT 3: Official government messages (25) ──
safe_messages += [("Government (Legit)", "Safe", m) for m in [
    "NADRA: Your CNIC renewal application #445521 received. Collection date: 15-Sep-2026.",
    "FBR: Your income tax return for FY2025-26 has been filed successfully.",
    "BISP: Aap ki Rs. 12,000 ki quarterly payment 1-Sep-2026 ko disburse ho gayi hai. Qareebi HBL branch se CNIC dikha kr hasil kren. Koi fee nahi.",
    "Ehsaas: Aap ki family ko monthly Rs. 14,000 ka wazifa approve ho gaya hai. Qareebi BISP center se CNIC ke saath tashreef layen. Koi advance payment nahi.",
    "Passport Office: Your passport application is under process. Expected delivery: 10 working days.",
    "PTA: Your device IMEI 356789012345678 is PTA approved and registered.",
    "SECP: Your company annual return filed successfully on 28-Aug-2026.",
    "Punjab Land Authority: Your fard request is processed. Collect from Patwari office.",
    "Sindh Revenue Board: Your sales tax return for August filed successfully.",
    "Excise: Your vehicle token tax paid for FY2026-27. Receipt emailed.",
    "CDA: Sector G-13 development update — road construction completed.",
    "Election Commission: Your voter registration is confirmed. Polling station: Govt School G-9.",
    "HEC: Your degree attestation application received. Processing time: 5 working days.",
    "PEMRA: Cable TV license renewal approved for M/s ABC Networks.",
    "LDA: Housing scheme ballot results published at lda.gov.pk",
    "KDA: Plot possession letter for Sector 45-B issued. Collect from KDA office.",
    "NADRA: Aap ka naya CNIC tayar hai. Nadra center se biometric krwa k collect kren.",
    "FBR: Active Taxpayer List updated. Verify at fbr.gov.atl",
    "نیب: احتیاطی پیغام — جعلی فون کالز سے ہوشیار رہیں۔ نیب کبھی فون نہیں کرتا۔",
    "Civil Aviation: Flight schedule update — Islamabad to Karachi, PK-305 on time.",
    "Punjab Police: Character certificate application received. Collect after 7 days.",
    "Ministry of Health: Vaccination drive schedule for September 2026 published.",
    "Pakistan Railways: Train ML-1 Awam Express on time. Arrival: 6:30 PM.",
    "NHA: Motorway M-5 open for traffic. Speed limit 120 km/h.",
    "State Bank: Policy rate maintained at 22%. Next review: October 2026.",
]]

# ── CAT 4: Personal messages (25) ──
safe_messages += [("Personal", "Safe", m) for m in [
    "Assalam o Alaikum! Kal sham ko dinner pe aao. Ghar pe biryani bana rahi hun.",
    "Bhai, Rs. 5000 bhej diye hain easypaisa se. Check karo.",
    "Ammi, main office se nikal gaya hun. 30 min mein ghar aaunga.",
    "Yaar kal cricket match dekhne chalein? Pakistan vs India T20.",
    "Baji, bacho ko school se le lena. Main late aaunga aaj.",
    "Abbu ne kaha hai weekend pe Naran chalte hain. Sab ready ho jao.",
    "Bhai meri salary aa gayi hai. Kal Rs. 10,000 wapis bhej dunga.",
    "Aapi, shopping mall chalain? Eid ki shopping krni hai.",
    "Dost, assignment complete kr li? Kal submit krni hai.",
    "Bhai ghar ka lock change krwa diya. Naya chabi kal de dunga.",
    "Assalam o Alaikum bhai, kaise hain? Bohat din ho gaye baat kiye.",
    "Phuppo ki tabiat kharab hai. Hospital le jana parega.",
    "Bhai Rs. 3000 ka bill pay kr diya. Receipt WhatsApp kr rahi hun.",
    "Yaar office mein meeting hai. Late ho jayega aaj.",
    "Beta, dawai le li? Doctor ne kaha tha time pe leni hai.",
    "Bhai, WiFi bill Rs. 3500 pay kr dena. Due date kal hai.",
    "Ammi ne kaha hai aaj jaldi aana. Mehman aa rahe hain.",
    "Bhai car ki servicing krwa li. Bill Rs. 8000 hua.",
    "Dost, naya restaurant try kren? Clifton mein khula hai.",
    "Baji, bacho ki school fees Rs. 15,000 kal jama krwa dena.",
    "Assalam o Alaikum. Kal Eidi kitni mili? Mujhe Rs. 5000 mili.",
    "Bhai mobile charger le aana. Mera kharab ho gaya.",
    "Yaar cricket ground book kr diya. Kal sham 5 baje khelte hain.",
    "Aapi, aap ki dress tailor se aa gayi. Rs. 2500 bill hua.",
    "Bhai, ghar ka electricity bill Rs. 12,000 aaya hai. Bohat zyada hai.",
]]

# ── CAT 5: Business/Professional (25) ──
safe_messages += [("Business", "Safe", m) for m in [
    "Meeting reminder: Quarterly review tomorrow at 10 AM. Conference Room B.",
    "HR: Your leave application for 5-Sep to 8-Sep approved.",
    "Payroll: Your salary slip for August 2026 emailed. Check inbox.",
    "IT Department: System maintenance scheduled for Sunday 2 AM to 6 AM.",
    "Project update: Phase 2 deliverables submitted on time. Client satisfied.",
    "Vendor payment of Rs. 150,000 processed. Expected credit in 2 business days.",
    "Invoice #2026-089 sent to client. Amount: Rs. 75,000. Due: 15-Sep-2026.",
    "Office announcement: Annual dinner on 20-Sep at Marriott Hotel.",
    "Team meeting rescheduled to 3 PM today. Please confirm attendance.",
    "Procurement: Purchase order #PO-2026-445 approved. Vendor notified.",
    "Expense report of Rs. 12,500 approved. Reimbursement in next payroll.",
    "Client feedback: Project delivery rated 4.5/5. Great work team!",
    "Office Wi-Fi password updated: Company2026!@. Connect to CorpNetwork.",
    "HR: Annual increment letters distributed. Check your email.",
    "Audit team visiting next week. Please prepare Q2 financial documents.",
    "New employee joining: Muhammad Hassan, Software Engineer, starting Monday.",
    "Board meeting minutes for August 2026 circulated. Review before Friday.",
    "Company picnic scheduled for October 15 at Lakeview Park. Families welcome.",
    "Quarterly sales target achieved: 115%. Bonus processing in September.",
    "Office renovation: Floor 3 closed for 2 weeks. Work from Floor 2.",
    "Compliance training mandatory for all staff. Deadline: 30-Sep-2026.",
    "Server migration completed. All systems operational.",
    "Performance reviews scheduled for October. Self-assessment due 15-Sep.",
    "Budget proposal for FY2026-27 due by 30-Sep. Department heads submit.",
    "Internship program: 10 interns joining from LUMS and NUST in October.",
]]

# ── CAT 6: Educational (25) ──
safe_messages += [("Education", "Safe", m) for m in [
    "LUMS: Your admission to MBA program confirmed. Orientation on 15-Sep-2026.",
    "NUST: Semester registration fee of Rs. 85,000 due by 10-Sep-2026.",
    "IBA: Mid-term exam schedule published. Check student portal.",
    "FAST University: Your GPA for Spring 2026 is 3.65. Dean's List.",
    "School notification: Parent-teacher meeting scheduled for Saturday 10 AM.",
    "University fee receipt: Rs. 45,000 paid for Fall 2026 semester.",
    "Board exams result: Your roll number 889900 scored 92% — 1st position.",
    "School bus route changed: Pickup time now 7:15 AM from Monday.",
    "Library book return reminder: 3 books due by 5-Sep-2026.",
    "Scholarship application deadline extended to 30-Sep-2026.",
    "Course registration: CS-401 Artificial Intelligence — Section A full.",
    "University: Convocation ceremony on 20-Oct-2026. Register by 30-Sep.",
    "School fees: Q2 installment of Rs. 25,000 due on 01-Oct-2026.",
    "Exam hall ticket downloaded. Roll No: 2026-MBA-0445.",
    "Research paper accepted: IEEE International Conference on AI 2026.",
    "Campus placement: 15 companies visiting next week. Register for interviews.",
    "University hostel: Room allotment published. Check student portal.",
    "Online course: Machine Learning specialization completed. Certificate issued.",
    "School annual day: 25-Nov-2026. Students to prepare performances.",
    "Tuition fee receipt: Rs. 12,000 paid for August 2026.",
    "University email: Password expires in 7 days. Reset at portal.university.edu.pk",
    "Lab equipment: Microscope #12 repaired. Available for use.",
    "Sports day: Athletics competition on 15-Oct. Register by 01-Oct.",
    "Alumni meet: Annual gathering on 05-Nov. RSVP by 15-Oct.",
    "PhD defense: Thesis submitted. Viva voce scheduled for 20-Oct-2026.",
]]

# ── CAT 7: Healthcare (25) ──
safe_messages += [("Healthcare", "Safe", m) for m in [
    "Aga Khan Hospital: Your appointment with Dr. Ahmed is confirmed for 5-Sep at 3 PM.",
    "Shaukat Khanum: Lab report ready. Collect from reception or download online.",
    "Pharmacy: Your prescription is ready. Total: Rs. 2,500. Collect from store.",
    "Health insurance: Claim #445521 approved. Rs. 45,000 settled.",
    "Vaccination reminder: Your child's MMR vaccine due on 10-Sep-2026.",
    "Dentist appointment: Teeth cleaning scheduled for 8-Sep at 11 AM.",
    "Hospital: Your MRI scan report is ready. Collect from radiology dept.",
    "Clinic: Follow-up visit reminder. Dr. Sara — 12-Sep at 2 PM.",
    "Medicine reminder: Take Metformin 500mg twice daily after meals.",
    "Blood test report: All values within normal range. Cholesterol: 180.",
    "Hospital bill: Rs. 15,000 for consultation and lab tests. Receipt attached.",
    "Eye checkup: Your prescription updated. New glasses ready at Optics store.",
    "Physiotherapy session #5 completed. Next appointment: 10-Sep at 4 PM.",
    "Medical store: Medicine order of Rs. 3,500 delivered.",
    "Hospital: Your discharge summary is ready. Collect from records department.",
    "Health checkup package: Rs. 5,000 comprehensive screening. Book online.",
    "Pediatrician: Baby's weight 8.5 kg. Growth on track. Next visit: 1 month.",
    "Surgery scheduled: Appendectomy on 15-Sep at 8 AM. Fasting from midnight.",
    "Psychologist session: Appointment confirmed for 11-Sep at 5 PM.",
    "X-ray report: No fracture detected. Soft tissue injury. Rest advised.",
    "Dental clinic: Root canal treatment completed. Crown appointment: 20-Sep.",
    "Lab: Your thyroid panel results — TSH 2.5, T3 normal, T4 normal.",
    "Hospital: Health card activated. Coverage: Rs. 500,000/year.",
    "Pharmacy delivery: Insulin pens delivered. Store at 2-8°C.",
    "Emergency: Ambulance dispatched. ETA 12 minutes. Stay calm.",
]]

# ── CAT 8: Utility/Bills (25) ──
safe_messages += [("Utility", "Safe", m) for m in [
    "K-Electric: Your electricity bill for August is Rs. 12,500. Due date: 15-Sep.",
    "SNGPL: Gas bill Rs. 3,500 for August 2026. Pay at any bank branch.",
    "PTCL: Your broadband bill of Rs. 3,000 is due on 10-Sep-2026.",
    "Water bill: Rs. 1,200 for August. Pay at WASP office or online.",
    "Sui Southern: Gas meter reading recorded. Bill will be generated in 3 days.",
    "Jazz postpaid: Bill of Rs. 2,500 for August. Due date: 20-Sep-2026.",
    "StormFiber: Monthly bill Rs. 3,500. Auto-payment processed successfully.",
    "Nayatel: Bill of Rs. 4,000 paid. Next billing cycle starts 01-Oct.",
    "K-Electric: Payment of Rs. 12,500 received. Thank you.",
    "PTCL: Your landline bill Rs. 800 is due on 15-Sep. Pay online at ptcl.com.pk",
    "SNGPL: Gas connection restoration scheduled for 5-Sep. Technician will visit.",
    "Water & Sanitation: Tanker delivered 5000 gallons. Charges: Rs. 2,000.",
    "Electricity: Load shedding schedule for your area — 2 PM to 4 PM daily.",
    "Sui Northern: Annual meter inspection on 10-Sep. Please ensure access.",
    "PTCL: Broadband speed upgraded to 50 Mbps. No change in monthly charges.",
    "K-Electric: Solar net-metering application approved. Installation next week.",
    "Gas bill: Rs. 5,200 for winter months. Pay by 20-Sep to avoid surcharge.",
    "Water bill: Arrears notice — Rs. 3,600 outstanding. Pay within 7 days.",
    "StormFiber: Service interruption on 8-Sep from 2 AM to 6 AM for maintenance.",
    "Nayatel: Speed test results — Download: 48 Mbps, Upload: 24 Mbps.",
    "Electricity: New transformer installed in your area. Power restored.",
    "SNGPL: Gas pressure low in your area. Maintenance in progress.",
    "PTCL: Fiber upgrade completed. New router installed.",
    "K-Electric: Complaint #88990011 resolved. Power restored to your area.",
    "Sui gas: Pipeline repair completed. Normal supply resumed.",
]]

# ── CAT 9: Social media/Platform notifications (25) ──
safe_messages += [("Social Media", "Safe", m) for m in [
    "Facebook: Ahmad sent you a friend request.",
    "Instagram: 5 people liked your photo.",
    "LinkedIn: Your profile was viewed 12 times this week.",
    "Twitter: @techpakistan mentioned you in a tweet.",
    "YouTube: New video from your subscription — Tech Review Pakistan.",
    "WhatsApp: 3 new messages in 'Family' group.",
    "TikTok: Your video got 1,500 views in 24 hours.",
    "Snapchat: Ali sent you a snap.",
    "Reddit: Your post in r/Pakistan got 45 upvotes.",
    "Pinterest: 10 new pins in your 'Recipes' board.",
    "Discord: 5 new messages in 'Gaming Squad' server.",
    "Telegram: Channel 'Crypto News' posted 3 new updates.",
    "Zoom: Meeting with 'Project Team' starts in 15 minutes.",
    "Slack: 8 unread messages in #general channel.",
    "GitHub: Pull request #45 merged successfully.",
    "Stack Overflow: Your answer received 12 upvotes.",
    "Medium: New article from author you follow: 'AI in Pakistan'.",
    "Spotify: Your weekly playlist is ready. 30 new songs.",
    "Netflix: New season of your favorite show is available.",
    "Amazon Prime: Your subscription renews on 15-Sep for Rs. 499.",
    "Google Photos: 50 new memories from 2 years ago.",
    "Dropbox: File 'report.pdf' shared with you by Ahmed.",
    "OneDrive: Storage usage 8 GB of 15 GB.",
    "Clubhouse: Room starting: 'Tech Startups in Pakistan' — 50 listeners.",
    "Threads: Your post got 200 likes. Keep posting!",
]]

# ── CAT 10: Tricky safe messages with scam-like keywords (25) ──
safe_messages += [("Tricky Safe", "Safe", m) for m in [
    "OLX: Aap ki listing 'Honda Civic 2019' ko 47 logon ne dekha. 3 messages aaye hain.",
    "Zameen.com: Property alert — Gulshan-e-Iqbal mein 3 naye 2-bed apartments listed.",
    "Daraz: Aap ki wishlist mein Samsung Galaxy S24 Ultra ki price Rs. 15,000 kam ho gayi hai.",
    "LinkedIn: Muhammad Hassan viewed your profile 3 times this week. 5 new connections.",
    "NEPRA: Bijli ke rates mein tabdeeli ka notification. September 2026 se Rs. 2.50/unit kami.",
    "State Life: Insurance policy #445521 matured. Rs. 500,000 claim approved. Visit branch with CNIC.",
    "EFU Insurance: Motor insurance renewal premium Rs. 8,500. Pay at efu.com.pk",
    "Jubilee Life: Pension fund statement — August 2026. Current value Rs. 2,500,000.",
    "PSX: KSE-100 index closed at 78,500 (+450 points). Your portfolio value: Rs. 1,200,000.",
    "Mutual fund: Your Meezan Islamic Fund units — NAV Rs. 125.50. Total value Rs. 500,000.",
    "Bank: Your fixed deposit Rs. 1,000,000 matured. Principal + profit Rs. 1,125,000 credited.",
    "NADRA: Aap ka CNIC 15-Oct-2026 ko expire ho raha hai. Nadra center ja kr renew kren.",
    "Tax consultant: Aap ka FBR return file ho gaya hai. Rs. 15,000 refund expected.",
    "Property dealer: Plot Rs. 5,000,000 mein bik gaya hai. Transfer documents ready.",
    "Insurance claim: Car accident case #77889. Approved amount Rs. 150,000.",
    "Salary increment: Your package revised to Rs. 120,000/month effective October 2026.",
    "Bonus: Annual performance bonus of Rs. 50,000 will be paid in September payroll.",
    "Commission: Your sales commission of Rs. 25,000 credited to your account.",
    "Rental income: Tenant paid Rs. 45,000 for September rent. Receipt generated.",
    "Investment: Your portfolio returned 18% this year. Current value Rs. 850,000.",
    "Freelance payment: Client transferred Rs. 75,000 via Payoneer. Available in 2 days.",
    "Business profit: Monthly profit share Rs. 35,000 credited to your account.",
    "Loan approved: Rs. 500,000 personal loan. EMI Rs. 12,500/month for 5 years.",
    "Credit card: Limit enhanced to Rs. 300,000. No additional charges.",
    "Remittance: Rs. 250,000 received from brother in Dubai via Western Union.",
]]

print(f"Total safe messages: {len(safe_messages)}")
assert len(safe_messages) == 250, f"Expected 250 safe, got {len(safe_messages)}"
